SET IDENTITY_INSERT Recommendations ON 

INSERT INTO Recommendations (Id,Nom,NomAr,CodeRecommendation,CodeRecommendationAr,Mecanisme,IdCycle,IdAxe,IdSousAxe,IdOrgane,IdVisite,IdPays,Etat,EtatAvancement,EtatAvancementChiffre,Observation,Complement,PieceJointe,Annee) values
(1300, N'Veiller à ce que les dispositions de la Constitution sur la liberté de la presse, la liberté d’opinion et d’expression et la liberté de réunion et d’association soient respectées, y compris pour les personnes qui veulent exprimer leurs vues sur la situation du et au Sahara occidental', N'ضمان احترام أحكام الدستور المتعلقة بحرية الصحافة وحرية الرأي والتعبير وحرية التجمع وتكوين الجمعيات، حتى للأشخاص الذين يريدون التعبير عن آرائهم بشأن الحالة في الصحراء الغربية ووضعها السياسي', N'R144.117', N'117.144', N'Examen périodique universal', 1, 5, 24, null, null, 89, N'En cours', N'', 30, N'', N'', N'', 2020),
(1301, N'Veiller à ce que les dispositions de la Constitution sur la liberté de la presse, la liberté d’opinion et d’expression et la liberté de réunion et d’association soient respectées, y compris pour les personnes qui veulent exprimer leurs vues sur la situation du et au Sahara occidental', N'ضمان احترام أحكام الدستور المتعلقة بحرية الصحافة وحرية الرأي والتعبير وحرية التجمع وتكوين الجمعيات، حتى للأشخاص الذين يريدون التعبير عن آرائهم بشأن الحالة في الصحراء الغربية ووضعها السياسي', N'R144.117', N'117.144', N'Examen périodique universal', 1, 5, 25, null, null, 89, N'En cours', N'', 30, N'', N'', N'', 2020),
(1302, N'Envisager de ratifier le deuxième Protocole facultatif se rapportant au Pacte international relatif aux droits civils et politiques', N'النظر في التصديق على البروتوكول الاختياري الثاني الملحق بالعهد الدولي الخاص بالحقوق المدنية والسياسية', N'R144.4', N'4.144', N'Examen périodique universal', 1, 5, 20, null, null, 65, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1303, N'Signer et ratifier le Protocole facultatif à la Convention sur l’élimination de toutes les formes de discrimination à l’égard des femmes', N'التوقيع والتصديق على البروتوكول الاختياري الثاني الملحق باتفاقية القضاء على جميع أشكال التمييز ضد المرأة ؛', N'R144.7', N'7.144', N'Examen périodique universal', 1, 6, 30, null, null, 49, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1304, N'Ratifier le Protocole facultatif à la Convention relative aux droits de l’enfant établissant une procédure de présentation de communications', N'التصديق على البروتوكول الاختياري لاتفاقية حقوق الطفل المتعلق بإجراء البلاغات', N'R144.9', N'9.144', N'Examen périodique universal', 1, 6, 32, null, null, 61, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(1305, N'Ratifier le Protocole facultatif à la Convention relative aux droits de l’enfant établissant une procédure de présentation de communications', N'التصديق على البروتوكول الاختياري لاتفاقية حقوق الطفل المتعلق بإجراء البلاغات', N'R144.9', N'9.144', N'Examen périodique universal', 1, 6, 32, null, null, 23, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(1306, N'Accélérer la procédure de ratification du Protocole facultatif à la Convention relative aux droits de l’enfant établissant une procédure de présentation de communications', N'تسريع عملية التصديق على البروتوكول الاختياري لاتفاقية حقوق الطفل المتعلق بإجراء تقديم البلاغات', N'R144.10', N'10.144', N'Examen périodique universal', 1, 6, 32, null, null, 38, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(1307, N'Ratifier la convention (no 189) de l’OIT sur les travailleuses et travailleurs domestiques, 2011', N'التصديق على اتفاقية العمال المنزليين، 2011 (رقم 189)، لمنظمة العمل الدولية', N'R144.16', N'16.144.', N'Examen périodique universal', 1, 4, 15, null, null, 72, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(1308, N'Ratifier le Protocole de 2014 à la Convention sur le travail forcé de l’Organisation internationale du Travail', N'التصديق على بروتوكول عام 2014 لاتفاقية منظمة العمل الدولية لإلغاء السخرة', N'R144.110 P2', N'110.144.ج.2', N'Examen périodique universal', 1, 4, 15, null, null, 80, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(1309, N'Adhérer aux conventions relatives au statut des apatrides et à la réduction des cas d’apatridie pour accorder la nationalité aux enfants qui, autrement, demeureraient apatrides et les incorporer dans le droit interne', N'الانضمام إلى الاتفاقيات المتعلقة بمركز الأشخاص عديمي الجنسية وإدراج أحكامها في قانونه الداخلي والحد من حالات انعدام الجنسية عن طريق منح الجنسية للأطفال الذين سيظلون بلا جنسية ما لم يُمنَحوا الجنسية المغربية', N'R144.242', N'242.144.', N'Examen périodique universal', 1, 5, 29, null, null, 51, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(1310, N'Adopter les amendements proposés au Code de procédure pénale pour assurer le respect des garanties en détention', N'اعتماد التعديلات المقترَحة لقانون المسطرة الجنائية من أجل ضمان احترام الضمانات والتدابير الوقائية أثناء الاحتجاز', N'R144.107', N'107.144', N'Examen périodique universal', 1, 5, 20, null, null, 40, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(1311, N'Créer et maintenir, en droit et dans la pratique, un environnement sûr et favorable pour la société civile et les défenseurs des droits de l’homme, y compris au Sahara occidental et en ce qui le concerne, grâce à une révision du Code pénal, et supprimer les restrictions à la liberté d’expression, revoir le système d’enregistrement des associations et de notification des réunions et veiller à une application cohérente des règles à tous les rassemblements pacifiques indépendamment de leur objet', N'إنشاء بيئة آمنة وممكّنة، في القانون والممارسة، والمحافظة عليها لفائدة المجتمع المدني والمدافعين عن حقوق الإنسان حتى في الصحراء الغربية وفيما يتعلق بها عن طريق مراجعة القانون الجنائي وإزالة القيود المفروضة على حرية التعبير واستعراض نظام تسجيل الجمعيات والإشعار بالتجمعات والتطبيق المتّسق للقواعد على جميع التجمعات السلمية بصرف النظر عن موضوعها', N'R144.120', N'120.144', N'Examen périodique universal', 1, 5, 25, null, null, 101, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1312, N'Réviser les dispositions du Code pénal sur le terrorisme et définir les infractions liées au terrorisme plus clairement et précisément', N'مراجعة أحكام القانون الجنائي المتعلقة بالإرهاب ووضعُ تعريف أوضح وأدق للجرائم المرتبطة بالإرهاب', N'R144.85', N'85.144', N'Examen périodique universal', 1, 5, 28, null, null, 45, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1313, N'Réexaminer complètement la législation nationale sur les migrations et l’asile', N'استعراض التشريعات الوطنية بشأن الهجرة واللجوء استعراضاً مفصلاً', N'R144.239', N'239.144', N'Examen périodique universal', 1, 6, 34, null, null, 44, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1314, N'Prendre des mesures pour mettre la définition de la torture en conformité avec celle énoncée dans la Convention contre la torture et autres peines ou traitements cruels, inhumains ou dégradants', N'اتخاذ خطوات لجعل تعريف التعذيب متوافقاً مع متطلبات اتفاقية مناهضة التعذيب وغيره من ضروب المعاملة أو العقوبة القاسية أو اللاإنسانية أو المهينة', N'R144.35', N'35.144', N'Examen périodique universal', 1, 5, 20, null, null, 40, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1315, N'Réviser les dispositions du Code pénal sur le terrorisme en vue de définir précisément les infractions liées au terrorisme et veiller à ce que la législation soit en conformité avec le Pacte international relatif aux droits civils et politiques', N'مراجعة أحكام القانون الجنائي المتعلقة بالإرهاب بغية وضع تعريف دقيق للجرائم المرتبطة بالإرهاب، وضمان أن تكون التشريعات متسقة مع العهد الدولي الخاص بالحقوق المدنية والسياسية', N'R144.86', N'86.144', N'Examen périodique universal', 1, 5, 28, null, null, 2, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1316, N'Examiner les dispositions du Code pénal relatives à la liberté d’expression à la lumière de l’article 19 du Pacte international relatif aux droits civils et politiques', N'استعراض أحكام القانون الجنائي المتعلقة بحرية التعبير بما يتوافق مع المادة 19 من العهد الدولي الخاص بالحقوق المدنية والسياسية', N'R144.116', N'116.14', N'Examen périodique universal', 1, 5, 24, null, null, 70, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1317, N'Veiller à ce que les dispositions pertinentes du Code pénal soient mises en conformité avec les obligations du Maroc en vertu du Pacte international relatif aux droits civils et politiques, en particulier en ce qui concerne la liberté d’expression et d’opinion', N'ضمان جعل الأحكام ذات الصلة من قانون المسطرة الجنائية أو من القانون الجنائي متماشية مع التزامات المغرب الناشئة عن العهد الدولي الخاص بالحقوق المدنية والسياسية ولا سيما فيما يتعلق بحرية الكلام والرأي', N'R144.112', N'112.144', N'Examen périodique universal', 1, 5, 24, null, null, 98, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1318, N'Accélérer le processus de révision du cadre juridique régissant les prisons afin de l’harmoniser avec les normes internationales', N'تسريع عملية مراجعة الإطار القانوني الذي ينظم السجون بهدف مواءمته مع المعايير الدولية', N'R144.103', N'103.144', N'Examen périodique universal', 1, 5, 21, null, null, 20, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1319, N'Accélérer le processus de révision du cadre législatif régissant les prisons en vue de l’harmoniser avec la Constitution de 2011 et les normes internationales', N'تسريع عملية مراجعة الإطار التشريعي الذي ينظم السجون بغية مواءمته مع دستور عام 2011 ومع المعايير الدولية', N'R144.106', N'106.144', N'Examen périodique universal', 1, 5, 21, null, null, 68, N'En cours', N'', 30, N'', N'', N'', 2020),
(1320, N'Accélérer l’examen du cadre juridique en matière de migration et d’asile afin de l’aligner sur le Pacte international relatif aux droits civils et politiques', N'تسريع استعراض الإطار القانوني المتعلق بالهجرة واللجوء بهدف مواءمته مع العهد الدولي الخاص بالحقوق المدنية والسياسية', N'R144.240', N'240.144', N'Examen périodique universal', 1, 6, 34, null, null, 67, N'En cours', N'', 30, N'', N'', N'', 2020),
(1321, N'Continuer d’adopter les mesures législatives et les politiques de protection nécessaires pour assurer l’éducation aux populations amazighes et sahraouies à tous les niveaux, ainsi que la pleine jouissance de leurs droits de manifester et de participer à la vie culturelle du pays, en préservant leurs traditions et leur identité', N'مواصلة اعتماد تدابير تشريعية وسياسات الحماية الضرورية لكفالة التعليم للسكان الأمازيغ والصحراويين في جميع المستويات، إلى جانب التمتع الكامل بحقوقهم في التظاهر والمشاركة في الحياة الثقافية في البلد بما يحفظ تقاليدهم وهويتهم', N'R144.235', N'235.144', N'Examen périodique universal', 1, 4, 14, null, null, 60, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1322, N'Améliorer l’accès aux services de santé dans les zones rurales, en particulier pour réduire la mortalité et la morbidité maternelles', N'زيادة الفرص في الحصول على خدمات الرعاية الصحية في الأرياف لأهداف منها الحد من معدلات وفيات الأمهات واعتلالهن', N'R144.163', N'163.144', N'Examen périodique universal', 1, 6, 30, null, null, 76, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1323, N'Continuer de promouvoir les soins et consultations prénatals pour réduire la nécessité du transport d’urgence au moment de l’accouchement et réduire ainsi le risque de décès chez les mères et les enfants', N'زيادة تحسين خدمات الرعاية الصحية قبل الولادة واستشارات الطبيب للحد من ضرورة النقل العاجل عند المخاض ومن ثم الحد من خطر وفيات الأمهات والأطفال', N'R144.164', N'164.144', N'Examen périodique universal', 1, 6, 30, null, null, 91, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1324, N'Continuer de promouvoir les soins et consultations prénatals pour réduire la nécessité du transport d’urgence au moment de l’accouchement et réduire ainsi le risque de décès chez les mères et les enfants', N'زيادة تحسين خدمات الرعاية الصحية قبل الولادة واستشارات الطبيب للحد من ضرورة النقل العاجل عند المخاض ومن ثم الحد من خطر وفيات الأمهات والأطفال', N'R144.164', N'164.144', N'Examen périodique universal', 1, 6, 32, null, null, 91, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1325, N'Prendre de nouvelles mesures ciblées pour promouvoir l’éducation inclusive pour tous', N'اتخاذ مزيد من التدابير المحددة الهدف بغية تعزيز التعليم الجامع', N'R144.165', N'165.144', N'Examen périodique universal', 1, 6, 33, null, null, 100, N'En cours', N'', 30, N'', N'', N'', 2020),
(1326, N'Établir un mécanisme national de prévention indépendant, efficace et doté de ressources suffisantes conformément au Protocole facultatif se rapportant à la Convention contre la torture et autres peines ou traitements cruels, inhumains ou dégradants', N'إنشاء آلية وقائية وطنية مستقلة وفعالة ومزوَّدة بقدر جيد من الموارد بما يتفق مع متطلبات البروتوكول الاختياري لاتفاقية مناهضة التعذيب وغيره من ضروب المعاملة أو العقوبة القاسية أو اللاإنسانية أو المهينة', N'R144.48', N'48.144', N'Examen périodique universal', 1, 5, 20, null, null, 40, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1327, N'Accélérer le processus de création du mécanisme national de prévention de la torture', N'تسريع عملية إنشاء الآلية الوطنية لمنع التعذيب', N'R144.49', N'49.144', N'Examen périodique universal', 1, 5, 20, null, null, 41, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1328, N'Rationaliser le processus de création du mécanisme national de prévention de la torture, et assurer une participation large et sans exclusive audit mécanisme', N'ترشيد عملية إنشاء الآلية الوطنية لمنع التعذيب عن طريق ضمان المشاركة الواسعة والشاملة في تلك الآلية', N'R144.50', N'50.144', N'Examen périodique universal', 1, 5, 20, null, null, 42, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1329, N'Intensifier les efforts pour combattre la torture et les autres mauvais traitements commis par des agents de l’État par la mise en place d’un mécanisme national indépendant et efficace pour la prévention de la torture', N'تكثيف الجهود لمكافحة حالات التعذيب وغيره من ضروب المعاملة السيئة على يد أعوان الدولة، وذلك بإنشاء آلية وطنية لمنع التعذيب تكون مستقلة وفعالة', N'R144.51', N'51.144', N'Examen périodique universal', 1, 5, 20, null, null, 31, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1330, N'Veiller à ce qu’un mécanisme national de prévention soit mis sur pied rapidement et que le mécanisme s’appuie sur une base juridique et reçoive les ressources humaines et les moyens financiers nécessaires pour s’acquitter de son mandat en toute indépendance et de manière efficace', N'ضمان الإسراع في إنشاء آلية وطنية لمنع التعذيب، وأن ترتكز تلك الآلية على أساس قانوني وأن تحصل على الموارد البشرية والمالية اللازمة لأداء وظيفتها على نحوٍ مستقل وكفء', N'R144.52', N'52.144', N'Examen périodique universal', 1, 5, 20, null, null, 90, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1331, N'Mettre en place un mécanisme de protection des droits des personnes handicapées', N'إنشاء آلية لحماية حقوق الأشخاص ذوي الإعاقة', N'R144.53', N'53.144', N'Examen périodique universal', 1, 6, 33, null, null, 56, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(1332, N'Créer un mécanisme national pour la protection des droits des personnes handicapées', N'إنشاء آلية وطنية لحماية حقوق الأشخاص ذوي الإعاقة', N'R144.54', N'54.144', N'Examen périodique universal', 1, 6, 33, null, null, 10, N'Réalisé', N'', 100, N'', N'', N'', 2020);
SET IDENTITY_INSERT Recommendations OFF
-->>>>>>>>>’>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
GO

INSERT INTO RecomOrgs (IdRecommendation, IdOrganisme, Date) values

(1300, 28, N'2020-12-01'),
(1300, 5, N'2020-12-01'),
(1301, 28, N'2020-12-01'),
(1301, 5, N'2020-12-01'),
(1302, 3, N'2020-12-01'),
(1303, 3, N'2020-12-01'),
(1304, 3, N'2020-12-01'),
(1305, 3, N'2020-12-01'),
(1306, 3, N'2020-12-01'),
(1307, 3, N'2020-12-01'),
(1307, 18, N'2020-12-01'),
(1308, 3, N'2020-12-01'),
(1308, 18, N'2020-12-01'),
(1309, 3, N'2020-12-01'),
(1310, 28, N'2020-12-01'),
(1311, 28, N'2020-12-01'),
(1311, 38, N'2020-12-01'),
(1312, 28, N'2020-12-01'),
(1313, 3, N'2020-12-01'),
(1313, 29, N'2020-12-01'),
(1314, 28, N'2020-12-01'),
(1314, 32, N'2020-12-01'),
(1315, 28, N'2020-12-01'),
(1315, 32, N'2020-12-01'),
(1316, 28, N'2020-12-01'),
(1316, 5, N'2020-12-01'),
(1316, 32, N'2020-12-01'),
(1317, 28, N'2020-12-01'),
(1317, 5, N'2020-12-01'),
(1317, 32, N'2020-12-01'),
(1318, 13, N'2020-12-01'),
(1319, 13, N'2020-12-01'),
(1320, 3, N'2020-12-01'),
(1320, 29, N'2020-12-01'),
(1321, 40, N'2020-12-01'),
(1322, 33, N'2020-12-01'),
(1323, 33, N'2020-12-01'),
(1324, 33, N'2020-12-01'),
(1325, 40, N'2020-12-01'),
(1326, 4, N'2020-12-01'),
(1327, 4, N'2020-12-01'),
(1328, 4, N'2020-12-01'),
(1329, 4, N'2020-12-01'),
(1330, 4, N'2020-12-01'),
(1331, 4, N'2020-12-01'),
(1332, 4, N'2020-12-01');