SET IDENTITY_INSERT Recommendations ON

INSERT INTO Recommendations (Id,Nom,NomAr,CodeRecommendation,CodeRecommendationAr,Mecanisme,IdCycle,IdAxe,IdSousAxe,IdOrgane,IdVisite,IdPays,Etat,EtatAvancement,EtatAvancementChiffre,Observation,Complement,PieceJointe,Annee) values
(2500, N'-   Adopter au plus vite le projet de loi n o 97.13 relatif à la protection et à la promotion des droits des personnes en situation de handicap, actuellement examiné par le 32, afin de garantir la protection juridique des personnes handicapées', N'', N'R92', N'', N'Procédure spéciale', null, 6, 33, null, 1, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2501, N'Pour les provinces marocaines du sud : 
- Offrir à la population locale les mêmes possibilités d’éducation et d’emploi, en vue de réduire la pauvreté et d’assurer la sécurité alimentaire et nutritionnelle de tous, conformément au droit international.', N'', N'R96P3', N'', N'Procédure spéciale', null, 4, 14, null, 1, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2502, N'Pour les provinces marocaines du sud : 
- Offrir à la population locale les mêmes possibilités d’éducation et d’emploi, en vue de réduire la pauvreté et d’assurer la sécurité alimentaire et nutritionnelle de tous, conformément au droit international.', N'', N'R96P3', N'', N'Procédure spéciale', null, 4, 15, null, 1, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2503, N'-   Prendre des mesures pour promouvoir une alimentation saine auprès des femmes et souligner les risques sanitaires associés au surpoids et à l’obésité', N'', N'R82', N'', N'Procédure spéciale', null, 6, 30, null, 1, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2504, N'-   Sensibiliser la population aux meilleures pratiques d’allaitement et aider les femmes et leur famille à adopter les meilleures pratiques en ce qui concerne l’alimentation des nourrissons et des jeunes enfants', N'', N'R83', N'', N'Procédure spéciale', null, 6, 30, null, 1, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2505, N'-   Mieux faire appliquer le Code international de commercialisation des substituts du lait maternel et créer un système de suivi indépendant.', N'', N'R84', N'', N'Procédure spéciale', null, 6, 30, null, 1, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2506, N'-   Faciliter, dans des conditions d’égalité, l’accès aux services de santé primaires, réduire la mortalité maternelle, juvénile et infantile et promouvoir de bonnes pratiques d’allaitement, conformément aux recommandations formulées par le Comité des droits de l’enfant', N'', N'R90P1', N'', N'Procédure spéciale', null, 6, 30, null, 1, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2507, N'-   Faciliter, dans des conditions d’égalité, l’accès aux services de santé primaires, réduire la mortalité maternelle, juvénile et infantile et promouvoir de bonnes pratiques d’allaitement, conformément aux recommandations formulées par le Comité des droits de l’enfant', N'', N'R90P1', N'', N'Procédure spéciale', null, 6, 32, null, 1, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2508, N'-   Renforcer la participation des femmes à l’examen des questions relatives au droit à l’alimentation, en particulier au niveau de la prise de décisions. Il faudrait prévoir la pleine participation des femmes vivant dans des zones reculées à la vie politique.', N'', N'R80', N'', N'Procédure spéciale', null, 6, 30, null, 1, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2509, N'-       Inviter le Rapporteur spécial sur les droits de l’homme des migrants à effectuer une visite de pays', N'', N'R86', N'', N'Procédure spéciale', null, 6, 34, null, 2, null, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(2510, N'-    Faire en sorte que les déclarations ou les aveux d’une personne privée de liberté, qui ne sont pas faits en présence d’un juge et avec l’assistance d’un avocat, n’aient aucune valeur probante dans les procédures contre cette personne ;', N'-          (د) ضمان ألا يكون لبيانات شخص مسلوب الحرية أو اعترافاته، غير تلك المدلى بها بحضور قاض أو بمساعدة محام، أي قوة مقنعة في الإجراءات المتعلقة بذلك الشخص؛', N'R88P4', N'ت.88.ف.4', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2511, N'-    Faire en sorte que les rapports établis par la police judiciaire pendant l’enquête restent irrecevables dans le cadre d’un procès tant que l’accusation, à qui incombe la charge de la preuve, n’a pas prouvé leur véracité et leur validité juridique, conformément au Code de procédure pénale ;', N'-          (ﻫ) التأكد من عدم قبول تقارير الشرطة القضائية المعدة إبّان مرحلة التحقيق في المحاكم حتى يثبت الادعاء صحتها وصلاحيتها القانونية وفقاً لقانون الإجراءات الجنائية؛', N'R88P5', N'ت.88.ف.5', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2512, N'faire en sorte que le personnel médical des lieux de détention soit véritablement indépendant des organes chargés d’appliquer la loi et reçoive une formation au sujet du Protocole d’Istanbul ;
-  autoriser l’accès à des examens médicaux indépendants effectués sans surveillance ni ingérence de la part d’agents chargés d’appliquer la loi ou de procureurs et d’assurer l’accès en temps voulu à des examens médicaux indépendants, au moment de l’arrestation, lors d’un transfert vers un autre lieu de détention ou sur demande;', N'ط) التأكد من أن العاملين الطبيين في أماكن الاحتجاز مستقلون تماماً عن موظفي إنفاذ القانون، ومدربون على بروتوكول اسطنبول؛ 
      الترخيص في الفحوص الطبية المستقلة دون تدخل العاملين في مجال إنفاذ القانون أو المدعين العامين أو حضورهم؛ وضمان تلك الفحوص في الوقت المناسب عند إلقاء القبض أو النقل إلى مكان احتجاز آخر أو عند الطلب؛', N'R88P9', N'ت.88.ف.9', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2513, N'-    prendre des mesures concrètes pour accélérer la ratification du Protocole facultatif à la Convention contre la torture', N'-          (ن) اتخاذ تدابير ملموسة لتسريع عملية التصديق على البروتوكول الاختياري الملحق باتفاقية مناهضة التعذيب.....', N'R88P14-1', N'ت.88.ف.14ج1', N'Procédure spéciale', null, 5, 20, null, 3, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2514, N'En ce qui concerne les migrants, les réfugiés et les demandeurs d ’ asile, le Rapporteur spécial recommande au
Gouvernement de collaborer plus étroitement avec le Haut- Commissariat des Nations Unies aux droits de l ’ homme, le
Rapporteur spécial sur les droits de l ’ homme des migrants et d ’ autres organismes des Nations Unies, tels que le
Haut-Commissariat des Nations Unies pour les réfugiés et:
a) De prendre toutes les mesures nécessaires pour prévenir d ’ autres violences et enquêter sur les informations faisant
état d ’ actes de violence subis par des migrants, des réfugiés et des demandeurs d ’ asile subsahariens;', N'فيما يتعلق بالمهاجرين واللاجئين وملتمسي اللجوء، يوصي المقرر الخاص الحكومة بأن توثق تعاونها مع مفوضية الأمم المتحدة السامية لحقوق الإنسان، والمقرر الخاص المعني بحقوق الإنسان للمهاجرين، ووكالات أخرى تابعة للأمم المتحدة، مثل مفوضية الأمم المتحدة السامية لشؤون اللاجئين؛ كما يوصيها بما يلي:
    أ) اتخاذ جمیع التدابیر اللازمة لمنع حدوث المزید من أعمال العنف، والتحقیق في التقاریر التي تتحدث عن تلك الأعمال في حق) المھاجرین واللاجئین وملتمسي اللجوء من الصحراء الغربیة؛', N'R90P1', N'ت.90.ف.1', N'Procédure spéciale', null, 6, 34, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2515, N'a) Modifier l’article 231-1 du Code pénal pour faire en sorte que la complicité ou le consentement exprès ou tacite des fonctionnaires chargés d’appliquer la loi et des forces de sécurité ou de toute autre personne agissant à titre officiel soient expressément visés', N'-          (أ) تعديل المادة 231-1 من القانون الجنائي بحيث تشمل تحديداً تواطؤ موظفي إنفاذ القانون أو غيرهم من الأشخاص الذين يتصرفون بصفة رسمية أو موافقتهم الصريحة أو الضمنية؛', N'R87P1', N'ت.87.ف.1', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2516, N'-    Modifier l’article 224 du Code pénal pour mettre la définition du fonctionnaire public en conformité avec la définition de l’agent de la 21 ou toute autre personne agissant à titre officiel qui figure dans la Convention contre la torture et autres peines ou traitements cruels, inhumains ou dégradants', N'-          (ب) تعديل المادة 224 من القانون الجنائي بحيث يتوافق تعريف الموظف العمومي مع تعريف موظف الخدمة المدنية أو غيره من الأشخاص الذين يعملون بصفة رسمية، الوارد في اتفاقية مناهضة التعذيب وغيره من ضروب المعاملة أو العقوبة القاسية أو اللاإنسانية أو المهينة؛', N'R87P2', N'ت.87.ف.2', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2517, N'-    veiller à ce qu’aucune personne reconnue coupable d’actes de torture ou faisant l’objet de poursuites pour de tels actes ne puisse bénéficier d’une mesure d’amnistie', N'-          (ج)  التأكد من عدم استفادة أي شخص مدان أو محكوم عليه بسبب ارتكابه جريمة التعذيب من أي عفو؛', N'R87P3', N'ت.87.ف.3', N'Procédure spéciale', null, 5, 20, null, 3, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2518, N'-    inclure dans le Code pénal une disposition expresse établissant que l’ordre d’un supérieur ou d’une autorité publique ne peut être invoqué pour justifier la torture, et mettre en place un mécanisme pour la protection des subordonnés qui refusent d’obéir à un ordre visant à torturer une personne en détention', N'-          (د) إدراج حكم محدد في القانون الجنائي ينص على أنه لا يجوز الاحتجاج بصدور أمر من موظف سام أو سلطة عامة لتبرير التعذيب، وتوفير آلية لحماية المرؤوسين الذين يرفضون إطاعة أوامر تعذيب أشخاص محتجزين لديهم؛', N'R87P4', N'ت.87.ف.4', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2519, N'-    modifier la loi (no 03-03) contre le terrorisme de façon à réduire le délai de garde à vue de quatre-vingt-seize heures (renouvelables deux fois)', N'-          (ﻫ) تعديل قانون مكافحة الإرهاب (03-03) لتقليص مدة الحبس الاحتياطي البالغة 96 يوماً (والقابلة للتجديد مرتين)؛', N'R87P5', N'ت.87.ف.5', N'Procédure spéciale', null, 5, 20, null, 3, null, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(2520, N'-    modifier l’article 290 du Code de procédure pénale de façon à appliquer aux infractions pénales la règle de la preuve qui régit les délits et contraventions afin que tous les rapports établis par la police pour des procès pénaux soient considérés comme des éléments de preuve parmi d’autres sans présomption quant à leur véracité', N'-          (و) مراجعة المادة 290 من قانون الإجراءات الجنائية كي تشمل معايير الاستدلال، التي تحكم الجرائم والتي يُعمل بها أصلاً، الجنحَ والمخالفات، بحيث يُتعامل مع جميع بيانات المحاكمات الجنائية التي تعدها الشرطة على أنها دليل واحد في جملة أدلة، دون افتراض صدقها؛', N'R87P6', N'ت.87.ف.6', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2521, N'-    modifier le Code de procédure pénale pour qu’il dispose qu’en cas d’allégation de torture ou de mauvais traitements, la charge de la preuve incombe à l’accusation, qui doit montrer au-delà de tout doute raisonnable que les aveux soumis au tribunal n’ont pas été obtenus par des moyens illicites', N'-          (ز) تعديل قانون الإجراءات الجنائية بحيث ينص على أنه متى كان ادعاء بالتعذيب أو سوء المعاملة، كان على الادعاء أن يثبت، دون أي شك معقول، أن كل اعتراف من الاعترافات لم يُنتزع بأساليب غير مشروعة؛', N'R87P7', N'ت.87.ف.7', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2522, N'-    modifier l’article 84 de la loi (no 23/98) sur les prisons de façon à habiliter les directeurs régionaux à autoriser les organisations de la société civile à visiter les établissements pénitentiaires, et de modifier l’article 10 du décret d’application de la loi no 23/98 afin d’élargir le champ des activités des organisations non gouvernementales dans ce domaine', N'-          (ح) تعديل المادة 84 من قانون السجون (رقم 23/98) بحيث يخول المديرين الإقليميين سلطة الترخيص لمنظمات المجتمع المدني بزيارة المؤسسة؛ وتعديل المادة 10 من المرسوم التنفيذي للقانون رقم 23/98 بحيث توسع نطاق أنشطة المنظمات غير الحكومية في هذا المجال؛', N'R87P8', N'ت.87.ف.8', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2523, N'-    modifier l’article 134 du Code pénal pour faire en sorte que les auteurs d’infraction souffrant d’une maladie mentale soient placés dans un établissement psychiatrique, quelle que soit la gravité de l’infraction commise', N'-          (ط) تعديل المادة 134 من القانون الجنائي بحيث تنص على إيداع جميع المجرمين المصابين بخلل عقلي في مصحة نفسية، بصرف النظر عن درجة خطورة الجرم.', N'R87P9', N'ت.87.ف.9', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2524, N'-    Modifier l’article 473 du Code de procédure pénale de façon à porter de 12 à 18 ans l’âge auquel un délinquant mineur peut être emprisonné et à souligner que l’emprisonnement des délinquants mineurs est une mesure exceptionnelle ;', N'فيما يتعلق بالأحداث، يوصي المقرر الخاص الحكومة بما يلي:  (ب) تعديل المادة 473 من قانون الإجراءات الجنائية لزيادة العمر الذي يُسمح فيه بسجن الحدث الجانح من 12 إلى 18 عاماً، والتشديد على أن سجن الأحداث الجانحين إجراء استثنائي؛', N'R91P2', N'ت.91.ف.2', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2525, N'-    Modifier l’article 473 du Code de procédure pénale de façon à porter de 12 à 18 ans l’âge auquel un délinquant mineur peut être emprisonné et à souligner que l’emprisonnement des délinquants mineurs est une mesure exceptionnelle ;', N'فيما يتعلق بالأحداث، يوصي المقرر الخاص الحكومة بما يلي:  (ب) تعديل المادة 473 من قانون الإجراءات الجنائية لزيادة العمر الذي يُسمح فيه بسجن الحدث الجانح من 12 إلى 18 عاماً، والتشديد على أن سجن الأحداث الجانحين إجراء استثنائي؛', N'R91P2', N'ت.91.ف.2', N'Procédure spéciale', null, 6, 34, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2526, N'-    Assurer, par des modifications apportées à la législation, que l’accès à un avocat choisi par le suspect lui-même soit garanti dès l’arrestation, sans surveillance policière et sans avoir à obtenir l’autorisation préalable du Procureur, y compris en cas de menace contre la sécurité et de terrorisme. Cet accès doit être accordé en application de la loi et tout fonctionnaire qui refuserait de l’accorder devrait être sanctionné', N'ب) التأكد، بواسطة تعديل التشريعات، من أن توكيل المحامين من اختيار المشتبه فيهم مكفول منذ اللحظة الأولى من إلقاء القبض، دون حضور محقق ودون اشتراط إذن من المدعي العام، بما في ذلك قضايا تهديد الأمن القومي والإرهاب. وينبغي منح ذلك الحق قانوناً، وتأديب كل موظف يحول دون ذلك؛', N'R88P2', N'ت.88.ف.2', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2527, N'-    mettre en place un mécanisme d’enquête pénale et de poursuites indépendant qui n’ait aucun lien avec l’organe chargé de l’enquête ou des poursuites dans la procédure engagée contre la victime présumée; de donner effet au droit de plainte et de faire en sorte que les défendeurs qui comparaissent devant le mécanisme aient une bonne chance de formuler leurs allégations au sujet des tortures et des mauvais traitements qu’ils ont pu subir', N'-          (ز) إنشاء آلية للتحقيق الجنائي والملاحقة تكون فعالة ومستقلة ولا ترتبط بالهيئة المكلفة بالتحقيق في الدعاوى المقامة على من يدعون أنهم ضحايا وبملاحقتهم؛ وإعمال الحق في الشكوى؛ والتأكد من إتاحة الفرصة أمام المدّعى عليهم الذين يمثلون أولاً أمام الآلية كي يتحدثوا عما يدعونه من تعرضهم للتعذيب أو سوء المعاملة؛', N'R88P7', N'ت.88.ف.7', N'Procédure spéciale', null, 5, 20, null, 3, null, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(2528, N'-    Fournir au Ministère de l’26 tout le soutien logistique et financier nécessaire pour lui permettre d’appliquer le projet envisagé par le Ministère de la justice et des libertés visant à effectuer un enregistrement vidéo de toutes les déclarations faites à la police pendant l’enquête et l’interrogatoire. De telles mesures ne doivent pas se substituer à la représentation légale pendant toutes les phases de l’interrogatoire mais la compléter', N'-          (ل) إمداد وزارة الداخلية بكل الدعم اللوجستي والمالي اللازم لتنفيذ مشروع وزير العدل والحريات الداعي إلى تسجيل جميع بيانات الشرطة بالصورة والصوت أثناء التحقيق والاستجواب. وينبغي النظر إلى هذا الأسلوب على أنه يكمل التمثيل القضائي في جميع مراحل الاستجواب؛', N'R88P12', N'ت.88.ف.12', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2529, N'-    Mettre en place des mécanismes de plainte indépendants, efficaces et accessibles dans tous les lieux de détention en installant des lignes d’assistance téléphonique ou des boîtes confidentielles de dépôt de plaintes, et de faire en sorte que chaque détenu ait un accès sans entrave et sans surveillance au procureur sur sa demande et que les plaignants ne soient pas soumis à des représailles', N'-          (م) إنشاء آليات شكوى مستقلة وفعالة وميسرة في جميع أماكن الاحتجاز بواسطة تركيب خطوط هاتف مباشرة أو صناديق لوضع الشكاوى سراً، وضمان اتصال كل محتجز بالمدعي العام دون عوائق أو مراقبة بناء على الطلب، وعدم الانتقام من الشاكين؛', N'R88P13', N'ت.88.ف.13', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2530, N'-    Créer un mécanisme national de prévention de la torture efficace conformément à l’article 17 du Protocole facultatif, et entamer un processus de consultation de toutes les parties prenantes sans exception, notamment les organisations de la société civile', N'-          (ن)  ....إنشاء آلية وقاية وطنية فعالة وفقاً للمادة 17 من البروتوكول الاختياري؛ وبدء عملية تشاور يشارك فيها جميع الفاعلين المعنيين بالموضوع، مثل منظمات المجتمع المدني؛', N'R88P14-2', N'ت.88.ف.14ج2', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2531, N'-    Ouvrir les crédits nécessaires pour doter le mécanisme national de prévention des ressources humaines et autres dont il a besoin pour inspecter régulièrement tous les lieux de détention, recevoir des plaintes, engager des poursuites et les suivre jusqu’à leur terme', N'-          (س) رصد ميزانية لإمداد آلية الوقاية الوطنية بما يكفي من موارد بشرية وغيرها حتى يتسنى لها تفتيش جميع أماكن الاحتجاز بانتظام، وتلقي الشكاوى، ورفع دعاوى ومتابعتها حتى نهايتها؛', N'R88P15', N'ت.88.ف.15', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2532, N'-    Renforcer la confiance et la coopération entre l’État et la société civile de façon que toutes les organisations non gouvernementales soient en mesure de collaborer de manière plus efficace avec les mécanismes nationaux et internationaux et d’effectuer un travail de sensibilisation sur la base de dossiers bien documentés', N'-          (ع) ترسيخ الثقة وتوثيق التعاون بين الدول والمجتمع المدني بحيث تستطيع المنظمات غير الحكومية العمل بمزيد من الفاعلية مع الآليات الوطنية والدولية، والدعوة على أساس حالات موثقة توثيقاً جيداً؛', N'R88P16', N'ت.88.ف.16', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2533, N'-    Faciliter l’accès des organisations de la société civile aux établissements pénitentiaires et de renforcer le partenariat avec ces institutions pour qu’elles puissent jouer leur rôle de sensibilisation et de propagation de la culture des droits de l’homme et contribuer à l’amélioration de la formation des superviseurs et du personnel des établissements pénitentiaires.', N'-          (ف) تسهيل زيارة منظمات المجتمع المدني الإصلاحيات، وتوطيد الشراكة معها لمساعدتها على أداء دورها في التوعية، ونشر ثقافة حقوق الإنسان، والمساهمة في الارتقاء بمستوى تدريب المشرفين عليها وموظفيها.', N'R88P17', N'ت.88.ف.17', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2534, N'Exercer un contrôle judiciaire sur les établissements pénitentiaires ; - Renforcer les pouvoirs des juges d’application de façon à leur permettre de contrôler de manière effective ces établissements, de surveiller l’application des peines et de vérifier leur validité ; - Renforcer le droit d’appel des personnes soumises à des mesures disciplinaires', N'فيما يتعلق بظروف الاحتجاز، يوصي المقرر الخاص الحكومة بما يلي: -  (د) فرض المراقبة القضائية على الإصلاحيات؛ وتدعيم سلطات القضاة المكلفين بتنفيذ الأحكام بحيث يستطيعون مراقبة تلك المؤسسات بفعالية، ورصد إنفاذ العقوبات، والتحقيق في صلاحيته؛ وتعزيز حق المتضررين من الإجراءات التأديبية في الاستئناف؛', N'R93P4', N'ت.93.ف.4', N'Procédure spéciale', null, 5, 20, null, 3, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2535, N'-    faciliter la surveillance exercée par les commissions régionales, au moyen d’inspections régulières et effectives des prisons et de la présentation de rapports sur la situation des prisons et des prisonniers, de façon à améliorer la situation dans les prisons et à donner effet aux droits des prisonniers ;', N'فيما يتعلق بظروف الاحتجاز، يوصي المقرر الخاص الحكومة بما يلي:   (ﻫ) تسهيل الرصد الذي تتولاه اللجان الإقليمية لتحسين الأوضاع في السجون، وإعمال حقوق السجناء، عن طريق الزيارات المنتظمة والفعالة إلى السجون، وتقديم التقارير عن أوضاع السجون والسجناء؛', N'R93P5', N'ت.93.ف.5', N'Procédure spéciale', null, 5, 20, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2536, N'-    Pour ce qui est des établissements psychiatriques, faire en sorte que le Bureau du Procureur général et le 4 effectuent des visites dans les établissements psychiatriques comme prévu par la loi.', N'بخصوص المصحات النفسية، يوصي المقرر الخاص الحكومة بما يلي: (ب) زيارة النيابة العامة والمجلس الوطني لحقوق الإنسان المصحات النفسية، عملاً بالقانون.', N'R94P2', N'ت.94.ف. 2', N'Procédure spéciale', null, 5, 20, null, 3, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2537, N'-    Pour ce qui est des établissements psychiatriques, faire en sorte que le Bureau du Procureur général et le 4 effectuent des visites dans les établissements psychiatriques comme prévu par la loi.', N'بخصوص المصحات النفسية، يوصي المقرر الخاص الحكومة بما يلي: (ب) زيارة النيابة العامة والمجلس الوطني لحقوق الإنسان المصحات النفسية، عملاً بالقانون.', N'R94P2', N'ت.94.ف. 2', N'Procédure spéciale', null, 4, 13, null, 3, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2538, N'En ce qui concerne les provinces marocaines du Sud -  L’établissement d’un mécanisme régional intergouvernementales de surveillance des droits de l’homme, robuste, comme une mesure importante visant à instaurer la confiance et qui peut contribuer à améliorer la situation en ce qui concerne le respect des droits de l’homme et, en particulier, l’interdiction de la torture et autres peines ou traitements cruels, inhumains ou dégradants.', N'فيما يتعلق بالأقاليم الجنوبية للمملكة المغربية، يوصي المقرر الخاص الحكومة بما يلي: (د)  من شأن المنطقة بكاملها أن تستفيد من إنشاء آلية حكومية دولية إقليمية متينة لحقوق الإنسان بوصفها إجراء مهماً لبناء الثقة قد ي��اعد على تحسين وضع التقيد بحقوق الإنسان، خاصة ما يتعلق بحظر التعذيب وغيره من ضروب المعاملة أو العقوبة القاسية أو اللاإنسانية أو المهينة.', N'R97P4', N'ت.97.ف.4', N'Procédure spéciale', null, 5, 20, null, 3, null, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(2539, N'-    modifier l’article 84 de la loi (no 23/98) sur les prisons de façon à habiliter les directeurs régionaux à autoriser les organisations de la société civile à visiter les établissements pénitentiaires, et de modifier l’article 10 du décret d’application de la loi no 23/98 afin d’élargir le champ des activités des organisations non gouvernementales dans ce domaine', N'-          (ح) تعديل المادة 84 من قانون السجون (رقم 23/98) بحيث يخول المديرين الإقليميين سلطة الترخيص لمنظمات المجتمع المدني بزيارة المؤسسة؛ وتعديل المادة 10 من المرسوم التنفيذي للقانون رقم 23/98 بحيث توسع نطاق أنشطة المنظمات غير الحكومية في هذا المجال؛', N'R87P8', N'ت.87.ف.8', N'Procédure spéciale', null, 5, 21, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2540, N'-    Faciliter l’accès des organisations de la société civile aux établissements pénitentiaires et de renforcer le partenariat avec ces institutions pour qu’elles puissent jouer leur rôle de sensibilisation et de propagation de la culture des droits de l’homme et contribuer à l’amélioration de la formation des superviseurs et du personnel des établissements pénitentiaires.', N'-          (ف) تسهيل زيارة منظمات المجتمع المدني الإصلاحيات، وتوطيد الشراكة معها لمساعدتها على أداء دورها في التوعية، ونشر ثقافة حقوق الإنسان، والمساهمة في الارتقاء بمستوى تدريب المشرفين عليها وموظفيها.', N'R88P17', N'ت.88.ف.17', N'Procédure spéciale', null, 5, 21, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2541, N'Exercer un contrôle judiciaire sur les établissements pénitentiaires ; - Renforcer les pouvoirs des juges d’application de façon à leur permettre de contrôler de manière effective ces établissements, de surveiller l’application des peines et de vérifier leur validité ; - Renforcer le droit d’appel des personnes soumises à des mesures disciplinaires', N'فيما يتعلق بظروف الاحتجاز، يوصي المقرر الخاص الحكومة بما يلي: -  (د) فرض المراقبة القضائية على الإصلاحيات؛ وتدعيم سلطات القضاة المكلفين بتنفيذ الأحكام بحيث يستطيعون مراقبة تلك المؤسسات بفعالية، ورصد إنفاذ العقوبات، والتحقيق في صلاحيته؛ وتعزيز حق المتضررين من الإجراءات التأديبية في الاستئناف؛', N'R93P4', N'ت.93.ف.4', N'Procédure spéciale', null, 5, 21, null, 3, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2542, N'-    faciliter la surveillance exercée par les commissions régionales, au moyen d’inspections régulières et effectives des prisons et de la présentation de rapports sur la situation des prisons et des prisonniers, de façon à améliorer la situation dans les prisons et à donner effet aux droits des prisonniers ;', N'فيما يتعلق بظروف الاحتجاز، يوصي المقرر الخاص الحكومة بما يلي:   (ﻫ) تسهيل الرصد الذي تتولاه اللجان الإقليمية لتحسين الأوضاع في السجون، وإعمال حقوق السجناء، عن طريق الزيارات المنتظمة والفعالة إلى السجون، وتقديم التقارير عن أوضاع السجون والسجناء؛', N'R93P5', N'ت.93.ف.5', N'Procédure spéciale', null, 5, 21, null, 3, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2543, N'-    modifier la loi (no 03-03) contre le terrorisme de façon à réduire le délai de garde à vue de quatre-vingt-seize heures (renouvelables deux fois)', N'-          (ﻫ) تعديل قانون مكافحة الإرهاب (03-03) لتقليص مدة الحبس الاحتياطي البالغة 96 يوماً (والقابلة للتجديد مرتين)؛', N'R87P5', N'ت.87.ف.5', N'Procédure spéciale', null, 5, 28, null, 3, null, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(2544, N'-    Envisager de ratifier la Convention no 189 de l’OIT sur les travailleuses et travailleurs domestiques.', N'', N'R96P2', N'', N'Procédure spéciale', null, 4, 15, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2545, N'-    Poursuivre la collaboration étroite avec les organisations internationales et les organismes des Nations Unies compétents, notamment avec le HCR et l’OIM, afin de permettre aux victimes de la traite de retourner saines et sauves dans leur pays, en tenant dûment compte, s’il y a lieu, de la nécessité de leur garantir une protection internationale.', N'', N'R95P1', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2546, N'collaborer avec les organisations internationales et bilatérales aux fins de l’hébergement et de l’indemnisation des victimes de la traite. 
Envisager la possibilité d’utiliser les revenus issus du blanchiment d’argent ou les avoirs confisqués aux trafiquants comme ressources complémentaires pour financer l’aide aux victimes', N'', N'R97', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2547, N'-    Accélérer l’adoption des modifications à apporter au Code pénal, puis à promulguer et à appliquer des textes législatifs spécifiques contre la traite, dans un délai déterminé', N'', N'R80P2', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2548, N'-    Tout projet de modification ou de loi relative à la traite des êtres humains devrait être axé sur une approche fondée sur les droits de l’homme et comporter des dispositions relatives à l’indemnisation des victimes et aux recours effectifs dont celles-ci disposent.', N'', N'R87', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2549, N'-    Le champ d’application de la législation du travail devrait être élargi de sorte que les employés de maison bénéficient d’une protection suffisante.', N'', N'R80P3/R88P1', N'', N'Procédure spéciale', null, 4, 15, null, 4, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2550, N'Une réforme pénale devrait être entreprise et des systèmes de protection des victimes et des témoins devraient être institués. 
- Parallèlement à la réforme pénale, des modifications devraient être apportées au Code pénal et un cadre juridique plus vaste devrait être établi, qui exempte les victimes de la traite des peines encourues pour prostitution, pour immigration illégale et pour d’autres infractions connexes résultant directement de la traite', N'', N'R92', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2551, N'-    Veiller à la pleine application, en droit interne, du Protocole additionnel à la Convention des Nations Unies contre la criminalité transnationale organisée visant à prévenir, réprimer et punir la traite des personnes, en particulier des femmes et des enfants, qui impose à l’État de prévenir et de combattre la traite des êtres humains.', N'', N'R80P1', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2552, N'En ce qui les provinces marocaines du sud :
- a) …………. prendre des mesures concrètes pour améliorer la situation des employés de maison et lutter contre le travail des enfants et l’exploitation sexuelle des femmes et des enfants', N'', N'R99P1-2', N'', N'Procédure spéciale', null, 6, 30, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2553, N'-    …De nouvelles mesures devraient être prises pour que les victimes de la traite qui ont besoin d’une protection internationale soient dûment identifiées et aiguillées vers le système d’asile, selon que de besoin.', N'', N'R95P2', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2554, N'-    Mettre au point, d’entente avec toutes les parties prenantes, notamment les organisations de la société civile, un plan national d’action qui définisse clairement les objectifs à atteindre et les responsabilités de chacun et fixe des indicateurs clairs permettant de mesurer les progrès accomplis et l’efficacité des mesures prises pour lutter contre la traite des êtres humains', N'', N'R81', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2555, N'créer un organisme national qui serait chargé de coordonner les différentes activités menées par les organismes gouvernementaux dans le domaine de lutte contre la traite
- envisager de nommer un rapporteur spécial, chargé de surveiller la mise en œuvre de la législation relative à la traite et des mesures prises dans ce domaine et de mesurer leurs effets sur la situation des droits de l’homme.', N'', N'R82', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2556, N'-    Mettre en place un système de détection adapté, doté de ressources suffisantes, devrait être mis en place. Ce système devrait comporter des outils et des protocoles spécifiques permettant de repérer les victimes de la traite', N'', N'R83P1', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2557, N'Étant donné que l’on ne dispose pas de données fiables au sujet de la traite, il est urgent de mettre au point un mécanisme de collecte de données sur les affaires de traite, ainsi que sur les formes de traite, les différentes manifestations de ce phénomène et les tendances observées dans ce domaine. 
- Ces données sont essentielles à l’élaboration de mesures réfléchies de lutte contre la traite.', N'', N'R84', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2558, N'-    le Gouvernement devrait faire beaucoup plus d’efforts pour protéger et aider toutes les victimes de la traite, y compris les hommes et les garçons, en veillant au plein respect de leurs droits de l’homme, et devrait faire en sorte que les enquêtes menées sur les affaires de traite soient axées sur une approche fondée sur les droits de l’homme.', N'', N'R85', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2559, N'-    Davantage de ressources, financières et autres, devraient être allouées à l’aide aux victimes de la traite, et des programmes et des institutions parrainés ou soutenus par l’État devraient être créés et développés de sorte que les victimes puissent bénéficier de soins à court et à long terme.', N'', N'R86', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2560, N'-    Les agents de l’Inspection du travail devraient être habilités à surveiller les conditions de travail de ces employés, qui sont souvent plus exposés que quiconque au risque d’être victimes de la traite.', N'', N'R88P2', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2561, N'-    La participation et la collaboration des organisations de la société civile sont essentielles dans le cadre de 35. À cet égard, des mesures devraient être prises immédiatement, d’une part, pour fournir l’appui nécessaire aux organisations de la société civile qui aident les victimes, notamment en leur proposant un accompagnement psychologique, et d’autre part, pour établir le cadre juridique requis. Les organisations de la société civile et les organismes d’aide aux victimes devraient être en mesure d’exercer leurs activités dans toutes les régions du pays.', N'', N'R98', N'', N'Procédure spéciale', null, 6, 35, null, 4, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2562, N'Retirer toutes les déclarations restantes au sujet de la Convention sur l’élimination de toutes les formes de discrimination à l’égard des femmes, en particulier celles concernant l’article 2 et le paragraphe 4 de l’article 15, ainsi que la réserve à cet instrument', N'', N'R89P2', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(2563, N'Signer et ratifier le Protocole facultatif à la Convention sur l’élimination de toutes les formes de discrimination à l’égard des femmes ou y adhérer, et ratifier la Convention pour la protection de toutes les personnes contre les disparitions forcées', N'', N'R89P3', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2564, N'Combler les lacunes dans la protection juridique des droits des femmes et des groupes qui ont besoin d’une protection particulière, notamment les travailleurs domestiques et les travailleurs migrants, et faire en sorte que les groupes de femmes vulnérables bénéficient de l’égale protection de la loi. 
- Les projets de loi sur la violence à l’égard des femmes et la violence au foyer devraient être réexaminés à la lumière des observations finales du Comité contre la torture. Le Code pénal, qui est en cours de modification, devrait être revu dans le sens du respect des principes et des normes internationaux et adopté. Ses articles 475 et 490 devraient être abrogés
- Entamer un examen complet de l’application de toutes les lois et dispositions préjudiciables aux femmes et aux filles, y compris, entre autres, le Code de la famille, le Code de la nationalité, le Code pénal et le Code du travail. Cet examen devrait se faire avec la participation active des organisations de la société civile, notamment celles qui ont suivi les décisions des tribunaux dans des affaires relatives au mariage précoce et à la polygamie ;', N'', N'R89P4P5', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2565, N'Accélérer l’élaboration des lois organiques appelées à définir les conditions et les modalités d’exercice, par tous les citoyens, femmes et hommes du droit de présenter des motions en matière législative et des pétitions aux pouvoirs publics; de telles lois devraient prévoir des mesures spéciales pour renforcer l’accès effectif des femmes pauvres et marginalisées à ce droit, y compris la mobilisation de ressources pour le renforcement des capacités des groupes locaux de femmes', N'', N'R91P1', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2566, N'Institutionnaliser, en modifiant les lois sur les élections, les mesures spéciales visant à augmenter le nombre de femmes aux postes électifs, aux niveaux national et local, de façon à satisfaire aux normes internationales ; 
- les listes nationales dans lesquelles un nombre déterminé de sièges est réservé aux femmes devraient être conservées et les quotas augmentés. 
- Les femmes devraient avoir la possibilité de présenter leur candidature pour une réélection sur les listes nationales. 
- Une augmentation des quotas, qui réponde aux normes internationales, devrait être effectuée dans les élections locales', N'', N'R91P2', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2567, N'Mettre toutes les lois nationales en conformité avec les instruments internationaux relatifs aux droits de l’homme auxquels le Maroc est partie et de modifier ou d’abroger les dispositions discriminatoires qui subsistent dans les lois nationales', N'', N'R89P1', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2568, N'Assurer l’accès au droit à la santé, y compris aux services de santé sexuelle et reproductive et d’information', N'', N'R93P7', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2569, N'Assurer l’accès à l’éducation pour les filles rurales, y compris par des mesures supplémentaires et efficaces pour faciliter leur participation dans l’enseignement primaire et secondaire.', N'', N'R93P8', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2570, N'Accélérer la création d’une autorité pour la parité et la lutte contre la discrimination à l’égard des femmes en tant qu’organisation faîtière pour consolider les acquis en matière d’égalité et d’élimination de la discrimination à l’égard des femmes. 
- Le futur organisme devrait avoir pour tâches d’établir le bilan des progrès accomplis, de repérer les problèmes persistants et de proposer et d’exécuter des mesures en vue d’accomplir d’autres progrès. 
- Le Gouvernement devrait assurer un processus de consultation vaste et ouvert avec toutes les parties prenantes en faisant fond sur le travail accompli par le Conseil national des droits de l’homme, et faire en sorte que cette autorité coopère avec lui', N'', N'R89P8', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2571, N'a) le Conseil national des droits de l’homme et d’autres institutions nationales indépendantes doivent intensifier leurs efforts volontaristes pour faire face à la discrimination à l’égard des femmes en droit et en pratique en tant que partie intégrante des processus de protection et de promotion des droits de l’homme et de bonne gouvernance, notamment par le biais de systèmes indépendants de surveillance des droits de l’homme accessibles à toutes les femmes;
b) Renforcer l’exécution de leurs mandats aux niveaux régional et local par des mesures spéciales pour assurer au niveau local l’accès des femmes qui sont victimes de multiples formes de discrimination.', N'', N'R90', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2572, N'c) Revoir la représentation des femmes au Conseil des ministres pour faire en sorte que les objectifs d’égalité formelle et effective entre les hommes et les femmes soient atteints ; 
d) Revoir les règles de procédure régissant la prise de décisions aux échelons supérieurs des organes exécutif, législatif et judiciaire pour faire en sorte que l’objectif de la parité soit pris en compte', N'', N'R91P3P4', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2573, N'Veiller à ce qu’une suite soit donnée aux recommandations de la commission consultative sur la régionalisation concernant l’égalité entre les sexes dans le cadre de la mise en place du système de gouvernance des régions et d’autres collectivités territoriales envisagé dans la Constitution; les fonds de développement social et de solidarité interrégionale prévus par la Constitution doivent intégrer dans leur travail les principes de la budgétisation axée sur la parité.', N'', N'R91P6', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2574, N'Les partis politiques instituent divers moyens de garantir l’intégration des femmes dans les listes électorales', N'', N'R92', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2575, N'Revoir le fonds social pour le développement créé en vertu de la Constitution afin qu’il consacre une part équitable de ses ressources aux femmes, en particulier aux femmes rurales et aux femmes victimes de violence, de façon à les aider à jouir de leurs droits fondamentaux', N'', N'R93P1', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2576, N'Prendre des mesures pour faire en sorte que les conseils locaux soient plus soucieux des questions de parité entre les sexes et de promouvoir, en tant que moyen d’autonomiser davantage la femme, la capacité individuelle et collective des femmes locales de participer véritablement à la vie publique au niveau local', N'', N'R93P2', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2577, N'Accélérer l’entrée en service du Fonds pour la famille et les déboursements pour aider les bénéficiaires qui sont dans le besoin
- Renouveler le programme Tamkine et assurer sa viabilité, et faire bénéficier de ses prestations les groupes de femmes rurales et d’autres femmes marginalisées', N'', N'R93P4P5', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2578, N'Elargir la protection juridique aux organisations caritatives qui fournissent une assistance et une protection aux groupes de femmes vulnérables et assurer un appui continu et d’une plus vaste portée de la part de l’État', N'', N'R93P6', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2579, N'Le Groupe de travail recommande au Conseil national des droits de l’homme et à d’autres organismes nationaux indépendants de mettre en place, là où il n’en existe pas, des mécanismes efficaces de surveillance et de protection sensibles à la condition des femmes et capables d’atteindre les communautés pauvres et rurales et, notamment, de faire face à la discrimination extrême dont sont victimes les travailleuses dans les champs de fraises du nord du Maroc.', N'', N'R94', N'', N'Procédure spéciale', null, 6, 30, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2580, N'-       S’assurer que tous les suspects aient le droit de bénéficier, dans la pratique, des autres garanties fondamentales prévues par la loi, notamment le droit d’être examiné par un médecin indépendant, de communiquer avec un proche ou un ami, d’être informés de leurs droits et des charges retenues contre eux, et d’être traduits devant un juge sans délai', N'', N'R83P2', N'', N'Procédure spéciale', null, 5, 20, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2581, N'-       Prendre des mesures concrètes et durables pour parachever le processus de ratification du Protocole facultatif à la Convention contre la torture', N'', N'R83P14P1', N'', N'Procédure spéciale', null, 5, 20, null, null, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2582, N'-       En ce qui concerne les migrants en situation irrégulière, réfugiés et demandeurs d’asile, travailler en coopération plus étroite avec le Haut-Commissariat des Nations Unies pour les réfugiés ; le Haut-Commissariat des Nations Unies aux droits de l’homme ; le Rapporteur spécial sur les droits de l’homme des migrants et d’autres organismes des Nations Unies', N'', N'R83P16', N'', N'Procédure spéciale', null, 6, 34, null, null, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2583, N'-       Modifier la loi antiterroriste (no 03-03) en vue de remédier à la définition vague du crime de terrorisme et de réduire la durée de la garde à vue qui est de quatre-vingt-seize heures renouvelables deux fois', N'', N'R83P3', N'', N'Procédure spéciale', null, 5, 28, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2584, N'Modifier le Code de procédure pénale pour indiquer qu’en cas d’allégation de torture ou de mauvais traitements, la charge de la preuve incombe à l’accusation qui devra prouver, hors de tout doute raisonnable, que les aveux n’ont pas été obtenus par des moyens illégaux. 
- Les allégations de torture et de mauvais traitements devraient être admises à n’importe quel stade du procès et les tribunaux devraient être tenus de lancer des enquêtes d’office chaque fois qu’il y a des motifs raisonnables de suspecter des actes de torture ou de mauvais traitements', N'', N'R83P4', N'', N'Procédure spéciale', null, 5, 20, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2585, N'-       Étudier l’amendement de l’article 473 du Code de procédure pénale visant à reculer l’âge auquel un jeune délinquant peut être incarcéré de12à 18 ans, et souligner que l’emprisonnement des jeunes délinquants est une mesure exceptionnelle ;', N'', N'R83P21', N'', N'Procédure spéciale', null, 6, 32, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2586, N'De nouvelles dispositions constitutionnelles, en particulier celles qui concernent les droits et la diversité culturels, devraient être effectivement appliquées au moyen de textes législatifs, y compris tous les décrets pertinents, comme le stipule la Constitution', N'ينبغي إنفاذ الأحكام الدستورية الجديدة، لا سيما تلك المتعلقة بالحقوق الثقافية والتنوع الثقافي، إنفاذاً فعالاً من خلال اعتماد قوانين، بما فيها جميع القوانين الفرعية المناسبة، مثلما ينص على ذلك الدستور. 
- تتطلب القوانين والتدابير الجديدة  المتعلقة بإنفاذ الأحكام الدستورية الجديدة، لا سيما تلك الخاصة بالحقوق الثقافية والتنوع الثقافي اعتماد سياسات واستراتيجيات مناسبة وينبغي أن تقترن بتدريب مناسب وتوجيه صحيح للمسؤولين المكلفين بتطبيقها.', N'R83P1', N'ت.83.ف.1', N'Procédure spéciale', null, 4, 12, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2587, N'Renforcer l’appui à la promotion et à la préservation de la culture amazighe en promulguant sans délai des lois donnant effet à la disposition constitutionnelle conférant à la langue amazighe le statut de langue officielle', N'(أ) زيادة الدعم المقدم من أجل تعزيز الثقافة الأمازيغية والحفاظ عليها من خلال ما يلي:
- سن قوانين فورية لإنفاذ الحكم الدستوري الذي يمنح اللغة الأمازيغية صفة رسمية؛', N'R86P1-1', N'ت.86.ف.1ج1', N'Procédure spéciale', null, 4, 12, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2588, N'Intensifier les efforts pour appliquer la Convention pour la sauvegarde du patrimoine culturel immatériel.', N'- الدفع قدما بالجهود فيما يتعلق بتنفيذ اتفاقية صون التراث الثقافي غير المادي.', N'R90P3', N'ت.90.ق.3', N'Procédure spéciale', null, 4, 12, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2589, N'-          envisager d’adopter une nouvelle loi reconnaissant le droit de chacun de choisir librement le prénom de ses enfants dans sa propre langue;', N'- التفكير أيضاً في اعتماد قانون جديد يقر حق كل شخص في اختيار اسم طفله بحرية بلغته الخاصة؛', N'R86P2-3', N'ت.86.ف.2ج3', N'Procédure spéciale', null, 5, 29, null, null, null, N'Réalisé', N'', 100, N'', N'', N'', 2020),
(2590, N'Abroger la circulaire no 122 du 7 janvier 2002 du Ministère de l’éducation nationale stipulant que le nom non arabe d’un certain nombre d’écoles doit être remplacé par un nom arabe, et d’abroger tout autre texte législatif ou réglementaire comparable', N'-    (ج) إلغاء مذكرة وزارة التربية رقم 122 المؤرخة 7 كانون الثاني/ يناير 2002 التي تنص على تغيير الأسماء غير العربية لعدد من المدارس بأسماء عربية، وإلغاء أي تشريعات أخرى من هذا القبيل. ....', N'R86P4-1', N'ت.86.ف.4ج1', N'Procédure spéciale', null, 4, 12, null, null, null, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(2591, N'Réviser les manuels scolaires d’histoire et d’autres disciplines afin de refléter la diversité du pays, en veillant à une représentation adéquate de la diversité culturelle entre les auteurs, ainsi qu’au sein du comité indépendant chargé d’approuver les manuels. De plus, les programmes de formation des enseignants devraient comprendre des méthodologies reflétant la richesse de la diversité culturelle marocaine de la manière la plus interactive et novatrice possible', N'-    (د) تنقيح مادة التاريخ وغيرها من المواد في الكتب المدرسية لتعبر عن التنوع الذي يزخر به البلد، مع ضمان تمثيل كافٍ للتنوع الثقافي بين المؤلفين، وكذلك في لجنة الاستعراض المستقلة التي توافق على الكتب المدرسية. وبالإضافة إلى ذلك، ينبغي أن تشمل برامج تدريب المدرسين منهجيات تعبر عن ثراء التنوع الثقافي المغربي بأكثر الأساليب تفاعلاً وابتكاراً.', N'R86P4', N'ت.86.ف.4', N'Procédure spéciale', null, 4, 12, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2592, N'Les nouvelles lois et mesures relatives à la mise en œuvre de nouvelles dispositions constitutionnelles, en particulier celles qui concernent les droits et la diversité culturels exigent l’adoption de politiques et stratégies pertinentes, et ceux qui sont chargés de mettre celles-ci en œuvre doivent recevoir une formation et des orientations à cet effet.', N'-       تتطلب القوانين والتدابير الجديدة  المتعلقة بإنفاذ الأحكام الدستورية الجديدة، لا سيما تلك الخاصة بالحقوق الثقافية والتنوع الثقافي اعتماد سياسات واستراتيجيات مناسبة وينبغي أن تقترن بتدريب مناسب وتوجيه صحيح للمسؤولين المكلفين بتطبيقها.', N'R83P2', N'ت.83.ف.2', N'Procédure spéciale', null, 4, 12, null, null, null, N'Non réalisé', N'', 0, N'', N'', N'', 2020),
(2593, N'Adoption d’une procédure plus efficace, plus simple et plus conviviale de présentation des projets culturels à l’INDH et aux autres institutions de développement est cruciale pour autonomiser le secteur culturel de la société civile et susciter une participation plus active aux niveaux régional et national.', N'-       اعتماد عملية أكثر فعالية وبساطة وسهولة في الاستعمال لتقديم الطلبات فيما يخص المشاريع الثقافية التي تدخل في إطار المبادرة الوطنية للتنمية البشرية وغيرها من الوكالات الإنمائية، لتمكين القطاع المدني الثقافي والسماح بمشاركة أكثر فعالية على الصعيدين الإقليمي والوطني.', N'R88P1', N'ت.88.ف.1', N'Procédure spéciale', null, 4, 12, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2594, N'Renforcer l’appui à la promotion et à la préservation de la culture amazighe en veillant à ce que les chaînes de télévision et stations de radio qui diffusent leurs programmes en langue arabe diffusent également au moins 30 % de ceux-ci en langue amazighe, comme le prévoit la loi; des mesures supplémentaires devraient aussi être prises pour élaborer des programmes aux niveaux national et régional afin d’appuyer les activités menées pour promouvoir la connaissance du patrimoine culturel et la diversité culturelle dans le cadre des émissions pédagogiques et destinées à la jeunesse et pour associer les médias nationaux à cette action', N'(أ) زيادة الدعم المقدم من أجل تعزيز الثقافة الأمازيغية والحفاظ عليها من خلال ما يلي:
- 5-ضمان قيام قنوات وسائط الإعلام التي تبث برامجها باللغة العربية ببث ما لا يقل عن 30 في المائة من برامجها باللغة الأمازيغية، مثلما ينص على ذلك القانون؛ وينبغي اتخاذ مزيد من التدابير لإعداد برامج على الصعيدين الوطني والإقليمي من أجل دعم الجهود الرامية إلى تعزيز معرفة التراث الثقافي والتنوع في البرامج التعليمية والشبابية، وتعبئة وسائط الإعلام الوطنية للدعوة إلى هذا النهج؛', N'R86P1-5', N'ت.86.ف1ج5', N'Procédure spéciale', null, 4, 12, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020),
(2595, N'- Mettre en place des mécanismes permettant une participation effective et digne de ce nom, notamment en matière de prise de décisions, de la population au recensement, à l’interprétation, à la promotion et à la protection du patrimoine culturel.', N'إنشاء آليات تسمح للأشخاص باتخاذ قرارات فعالة ومجدية والمشاركة في تحديد التراث الثقافي وتفسيره وتعزيزه وحمايته. 
- توفير الدعم القانوني والمالي والمؤسسي لمقترح "الكنوز البشرية الحية".', N'R90P1P2', N'ت.90.ف.1.ف.2', N'Procédure spéciale', null, 4, 12, null, null, null, N'En cours', N'', 30, N'', N'', N'', 2020);
SET IDENTITY_INSERT Recommendations OFF

-->>>>>>>>>’>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

INSERT INTO RecomOrgs (IdRecommendation, IdOrganisme, Date) values

(2500, 12, N'2020-12-01'),
(2501, 40, N'2020-12-01'),
(2501, 18, N'2020-12-01'),
(2501, 26, N'2020-12-01'),
(2501, 39, N'2020-12-01'),
(2501, 33, N'2020-12-01'),
(2502, 40, N'2020-12-01'),
(2502, 18, N'2020-12-01'),
(2502, 26, N'2020-12-01'),
(2502, 39, N'2020-12-01'),
(2502, 33, N'2020-12-01'),
(2503, 33, N'2020-12-01'),
(2504, 33, N'2020-12-01'),
(2505, 33, N'2020-12-01'),
(2506, 33, N'2020-12-01'),
(2507, 33, N'2020-12-01'),
(2508, 39, N'2020-12-01'),
(2508, 12, N'2020-12-01'),
(2508, 33, N'2020-12-01'),
(2509, 3, N'2020-12-01'),
(2509, 15, N'2020-12-01'),
(2510, 6, N'2020-12-01'),
(2511, 6, N'2020-12-01'),
(2512, 6, N'2020-12-01'),
(2512, 13, N'2020-12-01'),
(2513, 3, N'2020-12-01'),
(2514, 3, N'2020-12-01'),
(2515, 28, N'2020-12-01'),
(2515, 6, N'2020-12-01'),
(2515, 32, N'2020-12-01'),
(2516, 6, N'2020-12-01'),
(2516, 28, N'2020-12-01'),
(2516, 32, N'2020-12-01'),
(2517, 6, N'2020-12-01'),
(2517, 28, N'2020-12-01'),
(2517, 32, N'2020-12-01'),
(2518, 6, N'2020-12-01'),
(2518, 28, N'2020-12-01'),
(2518, 32, N'2020-12-01'),
(2519, 6, N'2020-12-01'),
(2519, 28, N'2020-12-01'),
(2519, 32, N'2020-12-01'),
(2520, 6, N'2020-12-01'),
(2520, 28, N'2020-12-01'),
(2520, 32, N'2020-12-01'),
(2521, 6, N'2020-12-01'),
(2521, 28, N'2020-12-01'),
(2521, 32, N'2020-12-01'),
(2522, 6, N'2020-12-01'),
(2522, 28, N'2020-12-01'),
(2522, 32, N'2020-12-01'),
(2523, 6, N'2020-12-01'),
(2523, 28, N'2020-12-01'),
(2523, 32, N'2020-12-01'),
(2524, 6, N'2020-12-01'),
(2524, 28, N'2020-12-01'),
(2524, 32, N'2020-12-01'),
(2525, 6, N'2020-12-01'),
(2525, 28, N'2020-12-01'),
(2525, 32, N'2020-12-01'),
(2526, 32, N'2020-12-01'),
(2527, 6, N'2020-12-01'),
(2527, 4, N'2020-12-01'),
(2528, 26, N'2020-12-01'),
(2528, 6, N'2020-12-01'),
(2529, 26, N'2020-12-01'),
(2529, 6, N'2020-12-01'),
(2529, 13, N'2020-12-01'),
(2529, 22, N'2020-12-01'),
(2530, 4, N'2020-12-01'),
(2531, 17, N'2020-12-01'),
(2531, 4, N'2020-12-01'),
(2532, 4, N'2020-12-01'),
(2532, 15, N'2020-12-01'),
(2533, 13, N'2020-12-01'),
(2534, 6, N'2020-12-01'),
(2534, 13, N'2020-12-01'),
(2535, 4, N'2020-12-01'),
(2535, 13, N'2020-12-01'),
(2536, 33, N'2020-12-01'),
(2536, 6, N'2020-12-01'),
(2536, 4, N'2020-12-01'),
(2537, 33, N'2020-12-01'),
(2537, 6, N'2020-12-01'),
(2537, 4, N'2020-12-01'),
(2538, 4, N'2020-12-01'),
(2538, 15, N'2020-12-01'),
(2538, 28, N'2020-12-01'),
(2538, 6, N'2020-12-01'),
(2538, 11, N'2020-12-01'),
(2539, 6, N'2020-12-01'),
(2539, 28, N'2020-12-01'),
(2539, 32, N'2020-12-01'),
(2540, 13, N'2020-12-01'),
(2541, 6, N'2020-12-01'),
(2541, 13, N'2020-12-01'),
(2542, 4, N'2020-12-01'),
(2542, 13, N'2020-12-01'),
(2543, 6, N'2020-12-01'),
(2543, 28, N'2020-12-01'),
(2543, 32, N'2020-12-01'),
(2544, 3, N'2020-12-01'),
(2544, 18, N'2020-12-01'),
(2545, 3, N'2020-12-01'),
(2545, 26, N'2020-12-01'),
(2545, 29, N'2020-12-01'),
(2546, 28, N'2020-12-01'),
(2546, 3, N'2020-12-01'),
(2546, 26, N'2020-12-01'),
(2546, 29, N'2020-12-01'),
(2547, 28, N'2020-12-01'),
(2547, 32, N'2020-12-01'),
(2548, 28, N'2020-12-01'),
(2548, 15, N'2020-12-01'),
(2548, 32, N'2020-12-01'),
(2549, 18, N'2020-12-01'),
(2550, 28, N'2020-12-01'),
(2550, 26, N'2020-12-01'),
(2550, 6, N'2020-12-01'),
(2550, 29, N'2020-12-01'),
(2550, 32, N'2020-12-01'),
(2551, 28, N'2020-12-01'),
(2551, 26, N'2020-12-01'),
(2551, 6, N'2020-12-01'),
(2552, 18, N'2020-12-01'),
(2552, 12, N'2020-12-01'),
(2553, 26, N'2020-12-01'),
(2553, 3, N'2020-12-01'),
(2554, 28, N'2020-12-01'),
(2554, 26, N'2020-12-01'),
(2554, 29, N'2020-12-01'),
(2554, 6, N'2020-12-01'),
(2554, 49, N'2020-12-01'),
(2555, 28, N'2020-12-01'),
(2556, 28, N'2020-12-01'),
(2556, 26, N'2020-12-01'),
(2556, 6, N'2020-12-01'),
(2556, 4, N'2020-12-01'),
(2557, 28, N'2020-12-01'),
(2557, 26, N'2020-12-01'),
(2557, 6, N'2020-12-01'),
(2557, 18, N'2020-12-01'),
(2557, 4, N'2020-12-01'),
(2558, 28, N'2020-12-01'),
(2558, 26, N'2020-12-01'),
(2558, 6, N'2020-12-01'),
(2559, 26, N'2020-12-01'),
(2559, 6, N'2020-12-01'),
(2560, 18, N'2020-12-01'),
(2561, 28, N'2020-12-01'),
(2561, 26, N'2020-12-01'),
(2562, 3, N'2020-12-01'),
(2562, 28, N'2020-12-01'),
(2563, 3, N'2020-12-01'),
(2563, 12, N'2020-12-01'),
(2563, 28, N'2020-12-01'),
(2564, 28, N'2020-12-01'),
(2564, 12, N'2020-12-01'),
(2564, 18, N'2020-12-01'),
(2564, 3, N'2020-12-01'),
(2564, 29, N'2020-12-01'),
(2564, 32, N'2020-12-01'),
(2565, 38, N'2020-12-01'),
(2566, 26, N'2020-12-01'),
(2566, 32, N'2020-12-01'),
(2567, 28, N'2020-12-01'),
(2567, 12, N'2020-12-01'),
(2567, 32, N'2020-12-01'),
(2568, 33, N'2020-12-01'),
(2569, 40, N'2020-12-01'),
(2570, 7, N'2020-12-01'),
(2570, 12, N'2020-12-01'),
(2570, 4, N'2020-12-01'),
(2571, 4, N'2020-12-01'),
(2572, 7, N'2020-12-01'),
(2572, 21, N'2020-12-01'),
(2572, 9, N'2020-12-01'),
(2573, 26, N'2020-12-01'),
(2573, 12, N'2020-12-01'),
(2574, 26, N'2020-12-01'),
(2574, 50, N'2020-12-01'),
(2575, 12, N'2020-12-01'),
(2575, 17, N'2020-12-01'),
(2576, 26, N'2020-12-01'),
(2577, 12, N'2020-12-01'),
(2578, 12, N'2020-12-01'),
(2579, 4, N'2020-12-01'),
(2579, 18, N'2020-12-01'),
(2580, 6, N'2020-12-01'),
(2581, 3, N'2020-12-01'),
(2582, 26, N'2020-12-01'),
(2582, 3, N'2020-12-01'),
(2583, 28, N'2020-12-01'),
(2583, 32, N'2020-12-01'),
(2584, 28, N'2020-12-01'),
(2584, 6, N'2020-12-01'),
(2584, 32, N'2020-12-01'),
(2585, 28, N'2020-12-01'),
(2585, 32, N'2020-12-01'),
(2586, 10, N'2020-12-01'),
(2586, 32, N'2020-12-01'),
(2587, 7, N'2020-12-01'),
(2588, 10, N'2020-12-01'),
(2589, 26, N'2020-12-01'),
(2589, 28, N'2020-12-01'),
(2589, 32, N'2020-12-01'),
(2590, 40, N'2020-12-01'),
(2591, 40, N'2020-12-01'),
(2592, 10, N'2020-12-01'),
(2593, 26, N'2020-12-01'),
(2593, 10, N'2020-12-01'),
(2594, 5, N'2020-12-01'),
(2594, 10, N'2020-12-01'),
(2595, 10, N'2020-12-01');

